server:
  port: 8082

spring:
  application:
    name: wallet-service

  datasource:
    url: jdbc:mysql://localhost:3306/wallet_db?createDatabaseIfNotExist=true
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

kafka:
  consumer:
    bootstrap-servers: localhost:29092
    group-id: wallet-group
    auto-offset-reset: earliest
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-deserializer: org.apache.kafka.common.serialization.StringDeserializer